# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
workspace 'Demo'
target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
  pod 'Bidali-iOS-SDK', :path => '../'

end
